-- Seed a comprehensive catalog of editable site_content keys (idempotent).
INSERT INTO public.site_content (key, value) VALUES
  ('settings.name', '"UPPAL"'::jsonb),
  ('settings.tagline', '"Intelligent design. Lasting impact."'::jsonb),
  ('settings.email', '"hello@uppaldesign.co.uk"'::jsonb),
  ('settings.phone', '"+44 7911 123456"'::jsonb),
  ('settings.altPhone', '"+44 7700 900203"'::jsonb),
  ('settings.address', '"71-75 Shelton Street, London, UK"'::jsonb),
  ('settings.studioAddress', '"Unit 3, Design House, London, UK"'::jsonb),
  ('nav.items', '[{"label":"Home","to":"/"},{"label":"About Us","to":"/about"},{"label":"Services","to":"/services"},{"label":"Projects","to":"/projects"},{"label":"Process","to":"/process"},{"label":"Blog","to":"/blog"},{"label":"Contact Us","to":"/contact"}]'::jsonb),
  ('home.hero.eyebrow', '"Architecture · Interiors · Planning"'::jsonb),
  ('home.hero.title', '"Crafting Spaces That Inspire and Endure."'::jsonb),
  ('home.hero.subtitle', '"Premium architecture & interior design across the UK."'::jsonb),
  ('home.hero.cta', '"Start a project"'::jsonb),
  ('home.intro.heading', '"Design that respects light, space and people."'::jsonb),
  ('home.intro.body', '"From planning approvals to handover, we deliver thoughtful, buildable architecture across residential, commercial and hospitality."'::jsonb),
  ('about.hero.eyebrow', '"About Us"'::jsonb),
  ('about.hero.title', '"Designing the future of British architecture."'::jsonb),
  ('about.hero.subtitle', '"15+ years of award-winning design across the UK."'::jsonb),
  ('about.story.heading', '"Our story"'::jsonb),
  ('about.story.body', '"Founded in London, Uppal Design has grown into a multidisciplinary studio shaping spaces that balance function, beauty and longevity."'::jsonb),
  ('about.mission.heading', '"Our mission"'::jsonb),
  ('about.mission.body', '"To deliver intelligent design that respects context, climate and the people who use it."'::jsonb),
  ('about.founder.quote', '"Architecture is not what we build. It is how people feel inside it."'::jsonb),
  ('services.hero.eyebrow', '"What we do"'::jsonb),
  ('services.hero.title', '"Full-service architecture & interiors."'::jsonb),
  ('services.hero.subtitle', '"Planning, design, visualisation and delivery — under one roof."'::jsonb),
  ('services.why.heading', '"Why choose us"'::jsonb),
  ('services.cta.title', '"Have a project in mind?"'::jsonb),
  ('services.cta.body', '"Let''s talk through your brief, your site, and what you''re trying to achieve."'::jsonb),
  ('services.cta.button', '"Start a project"'::jsonb),
  ('process.hero.eyebrow', '"Our Process"'::jsonb),
  ('process.hero.title', '"A clear five-stage process, from concept to completion."'::jsonb),
  ('process.hero.subtitle', '"Predictable timelines, transparent fees, and no surprises."'::jsonb),
  ('process.principles.heading', '"Principles that guide every project"'::jsonb),
  ('projects.hero.eyebrow', '"Selected Work"'::jsonb),
  ('projects.hero.title', '"Projects shaped by site, brief and craft."'::jsonb),
  ('projects.hero.subtitle', '"A snapshot of recent residential, commercial and hospitality work."'::jsonb),
  ('blog.hero.eyebrow', '"Journal"'::jsonb),
  ('blog.hero.title', '"Notes on architecture, interiors and living well."'::jsonb),
  ('blog.hero.subtitle', '"Articles, studio news and field notes from the Uppal team."'::jsonb),
  ('contact.hero.eyebrow', '"Get in touch"'::jsonb),
  ('contact.hero.title', '"Tell us about your project."'::jsonb),
  ('contact.hero.subtitle', '"We respond to every enquiry within one working day."'::jsonb),
  ('contact.address', '"Churchill House, 1 London Rd, Slough SL3 7RL, UK"'::jsonb),
  ('contact.email', '"info@uppaldb.co.uk"'::jsonb),
  ('contact.phone', '"+44 7547 487675"'::jsonb),
  ('contact.hours', '"Mon – Fri · 9:00 – 18:00"'::jsonb),
  ('footer.brand.tagline', '"Intelligent design. Lasting impact."'::jsonb),
  ('footer.copyright', '"© Uppal Design. All rights reserved."'::jsonb),
  ('footer.columns', '[{"heading":"Studio","links":[{"label":"About","to":"/about"},{"label":"Process","to":"/process"},{"label":"Team","to":"/team"},{"label":"Careers","to":"/contact"}]},{"heading":"Work","links":[{"label":"Projects","to":"/projects"},{"label":"Services","to":"/services"},{"label":"Blog","to":"/blog"}]},{"heading":"Contact","links":[{"label":"Get in touch","to":"/contact"},{"label":"hello@uppaldesign.co.uk","to":"mailto:hello@uppaldesign.co.uk"}]}]'::jsonb),
  ('chatbot.greeting', '"Hi, I''m the Uppal concierge. Ask about services, projects or estimates."'::jsonb),
  ('collection.testimonials', '[{"quote":"Uppal turned our planning headache into a delight. Clear, kind, and brilliant.","author":"Priya & James","role":"Homeowners, Surrey"},{"quote":"They understood our brand the moment we briefed them. The space sells the experience.","author":"Marcus L.","role":"Founder, Hospitality Group"},{"quote":"On time, on budget, and the renders matched the build to the millimetre.","author":"Sarah K.","role":"Property Developer, London"}]'::jsonb),
  ('collection.team_leads', '[{"name":"Ar. Harpreet Uppal","role":"Founder & Principal Architect","image":""},{"name":"Ar. Simran Kaur","role":"Senior Architect","image":""},{"name":"Ar. Gurpreet Sandhu","role":"Project Director","image":""},{"name":"Ar. Arvind Sharma","role":"BIM Coordinator","image":""}]'::jsonb),
  ('collection.team_members', '[{"name":"Ar. Kuhan Mehta","role":"Project Architect"},{"name":"Ar. Neha Rawal","role":"Interior Architect"},{"name":"Ar. Karan Malhotra","role":"Design Architect"},{"name":"Ar. Pooja Sharma","role":"Landscape Architect"},{"name":"Ar. Manav Sethi","role":"BIM Specialist"},{"name":"Ar. Vivek Rao","role":"Technical Architect"},{"name":"Ar. Isha Verma","role":"3D Visualiser"},{"name":"Ar. Aditya Kapoor","role":"Design Researcher"},{"name":"Ar. Mehak Arora","role":"Documentation Lead"},{"name":"Ar. Sahil Grover","role":"Estimation Coordinator"}]'::jsonb),
  ('collection.stats', '[{"value":"250+","label":"Projects completed"},{"value":"15+","label":"Years of experience"},{"value":"98%","label":"Client satisfaction"},{"value":"20+","label":"Awards won"},{"value":"50+","label":"Expert team"}]'::jsonb),
  ('collection.values', '["Collaboration","Innovation","Excellence","Sustainability","Integrity","Growth"]'::jsonb),
  ('collection.process_steps', '[{"number":"01","title":"Concept","subtitle":"Ideation & Research","description":"We begin by understanding your vision, property constraints, and goals."},{"number":"02","title":"Planning","subtitle":"Design & Development","description":"Layouts are refined around planning intent, functionality and budget."},{"number":"03","title":"Visualization","subtitle":"3D Modeling & Rendering","description":"Detailed visualisations help you understand the space with confidence."},{"number":"04","title":"Documentation","subtitle":"Drawings & Approvals","description":"Technical information prepared for approvals, tendering and delivery."},{"number":"05","title":"Construction","subtitle":"Build & Deliver","description":"Site coordination, quality control, timely delivery and smooth handover."}]'::jsonb)
ON CONFLICT (key) DO NOTHING;